import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const tvProducts = [
  // ==========================================
  // 1. SAMSUNG (2022 - 2026 Models)
  // ==========================================
  {
    id: "TV-101",
    name: "Samsung OLED S95D 4K Smart TV (2024)",
    brand: "Samsung",
    category: "TVs",
    basePrice: 4200,
    sizes: "55 Inch (+AED 0) | 65 Inch (+AED 1200) | 77 Inch (+AED 2800)",
    colors: "Titan Black",
    shortDescription: "Glare-Free OLED 4K Smart TV with NQ4 AI Gen2 Processor & 144Hz.",
    description: "Samsung's flagship 2024 OLED TV. Features OLED Glare-Free tech, NQ4 AI Gen2 processor, Pantone Validated colors, Dolby Atmos, and Motion Xcelerator 144Hz for ultimate gaming and cinema.",
    frontViewImage: "/products/samsung-s95d-front.webp",
    sideViewImage: "/products/samsung-s95d-side.webp",
    backViewImage: "/products/samsung-s95d-back.webp",
  },
  {
    id: "TV-102",
    name: "Samsung Neo QLED 4K QN90D (2024)",
    brand: "Samsung",
    category: "TVs",
    basePrice: 3500,
    sizes: "55 Inch (+AED 0) | 65 Inch (+AED 900) | 75 Inch (+AED 2100) | 85 Inch (+AED 3600)",
    colors: "Titan Black",
    shortDescription: "Quantum Mini LED 4K Smart TV with Neo Quantum HDR+ & Real Depth Enhancer Pro.",
    description: "Ultra-precise Quantum Mini LED backlighting. Powered by NQ4 AI Gen2 processor, Anti-Reflection coating, Dolby Atmos, and 144Hz refresh rate.",
    frontViewImage: "/products/samsung-qn90d-front.webp",
    sideViewImage: "/products/samsung-qn90d-side.webp",
    backViewImage: "/products/samsung-qn90d-back.webp",
  },
  {
    id: "TV-103",
    name: "Samsung Neo QLED 8K QN900C (2023)",
    brand: "Samsung",
    category: "TVs",
    basePrice: 4800,
    sizes: "65 Inch (+AED 0) | 75 Inch (+AED 2500) | 85 Inch (+AED 4500)",
    colors: "Infinity One Black",
    shortDescription: "8K Quantum Mini LED TV with Infinity Screen & Neural Quantum 8K Processor.",
    description: "Nearly borderless Infinity Screen design. Neural Quantum Processor 8K with AI Upscaling, Quantum Matrix Pro, and Attachable Slim One Connect box.",
    frontViewImage: "/products/samsung-qn900c-front.webp",
    sideViewImage: "/products/samsung-qn900c-side.webp",
    backViewImage: "/products/samsung-qn900c-back.webp",
  },
  {
    id: "TV-104",
    name: "Samsung The Frame LS03C QLED TV (2023)",
    brand: "Samsung",
    category: "TVs",
    basePrice: 2200,
    sizes: "43 Inch (+AED 0) | 50 Inch (+AED 300) | 55 Inch (+AED 600) | 65 Inch (+AED 1300) | 75 Inch (+AED 2400)",
    colors: "Teak, Walnut, White, Sand Gold",
    shortDescription: "Matte Display Art TV with customizable magnetic bezels & QLED 4K.",
    description: "Transforms your TV into a gallery piece when off. Features Matte Display technology that eliminates reflections, Quantum Dot 100% color volume, and slim fit wall mount.",
    frontViewImage: "/products/samsung-frame-front.webp",
    sideViewImage: "/products/samsung-frame-side.webp",
    backViewImage: "/products/samsung-frame-back.webp",
  },
  {
    id: "TV-105",
    name: "Samsung Neo QLED 4K QN90B (2022)",
    brand: "Samsung",
    category: "TVs",
    basePrice: 2600,
    sizes: "55 Inch (+AED 0) | 65 Inch (+AED 700) | 75 Inch (+AED 1600)",
    colors: "Titan Black",
    shortDescription: "2022 Flagship Mini LED 4K TV with Neo Quantum Processor 4K.",
    description: "Quantum Matrix Technology with Mini LEDs, Neo Quantum Processor 4K, Object Tracking Sound (OTS+), and Motion Xcelerator Turbo+ for 4K 120Hz gaming.",
    frontViewImage: "/products/samsung-qn90b-front.webp",
    sideViewImage: "/products/samsung-qn90b-side.webp",
    backViewImage: "/products/samsung-qn90b-back.webp",
  },
  {
    id: "TV-106",
    name: "Samsung Crystal UHD 4K CU8000 (2023)",
    brand: "Samsung",
    category: "TVs",
    basePrice: 1300,
    sizes: "50 Inch (+AED 0) | 55 Inch (+AED 250) | 65 Inch (+AED 700) | 75 Inch (+AED 1400)",
    colors: "Black",
    shortDescription: "AirSlim Design 4K Smart TV with Dynamic Crystal Color & Crystal Processor 4K.",
    description: "Ultra-thin AirSlim profile, Dynamic Crystal Color with 1 billion shades, Crystal Processor 4K upscaling, and Smart Hub with built-in voice assistants.",
    frontViewImage: "/products/samsung-cu8000-front.webp",
    sideViewImage: "/products/samsung-cu8000-side.webp",
    backViewImage: "/products/samsung-cu8000-back.webp",
  },

  // ==========================================
  // 2. LG (2022 - 2026 Models)
  // ==========================================
  {
    id: "TV-201",
    name: "LG OLED evo C4 4K Smart TV (2024)",
    brand: "LG",
    category: "TVs",
    basePrice: 3800,
    sizes: "42 Inch (+AED 0) | 48 Inch (+AED 300) | 55 Inch (+AED 800) | 65 Inch (+AED 1800) | 77 Inch (+AED 3400)",
    colors: "Dark Titan",
    shortDescription: "2024 OLED evo TV with α9 AI Processor Gen7, Brightness Booster & 144Hz.",
    description: "LG's benchmark OLED evo TV. Powered by α9 AI Processor Gen7, Brightness Booster, 100% color fidelity, webOS 24 with 5 years of OS updates, NVIDIA G-Sync & AMD FreeSync Premium.",
    frontViewImage: "/products/lg-c4-front.webp",
    sideViewImage: "/products/lg-c4-side.webp",
    backViewImage: "/products/lg-c4-back.webp",
  },
  {
    id: "TV-202",
    name: "LG OLED evo G4 Gallery Edition (2024)",
    brand: "LG",
    category: "TVs",
    basePrice: 5100,
    sizes: "55 Inch (+AED 0) | 65 Inch (+AED 1600) | 77 Inch (+AED 3800) | 83 Inch (+AED 5800)",
    colors: "Light Steel Silver",
    shortDescription: "Flagship OLED evo TV with Micro Lens Array (MLA) Brightness Booster Max.",
    description: "The ultimate OLED display with α11 AI Processor 4K, Brightness Booster Max (MLA technology) for up to 150% brighter picture, zero-gap wall mount design, and 5-year panel warranty.",
    frontViewImage: "/products/lg-g4-front.webp",
    sideViewImage: "/products/lg-g4-side.webp",
    backViewImage: "/products/lg-g4-back.webp",
  },
  {
    id: "TV-203",
    name: "LG OLED evo C3 4K Smart TV (2023)",
    brand: "LG",
    category: "TVs",
    basePrice: 3100,
    sizes: "48 Inch (+AED 0) | 55 Inch (+AED 600) | 65 Inch (+AED 1400) | 77 Inch (+AED 2900)",
    colors: "Dark Titan",
    shortDescription: "Self-lit OLED evo TV with α9 AI Processor Gen6 & Dolby Vision IQ.",
    description: "Self-lit OLED pixels delivering infinite contrast and perfect black. Powered by α9 AI Processor Gen6, Brightness Booster, 0.1ms response time, and 4 HDMI 2.1 ports.",
    frontViewImage: "/products/lg-c3-front.webp",
    sideViewImage: "/products/lg-c3-side.webp",
    backViewImage: "/products/lg-c3-back.webp",
  },
  {
    id: "TV-204",
    name: "LG OLED evo C2 4K TV (2022)",
    brand: "LG",
    category: "TVs",
    basePrice: 2400,
    sizes: "42 Inch (+AED 0) | 48 Inch (+AED 300) | 55 Inch (+AED 600) | 65 Inch (+AED 1200)",
    colors: "Dark Silver",
    shortDescription: "Award-winning 2022 OLED evo TV with α9 Gen5 AI Processor 4K.",
    description: "Slim bevel design with OLED evo panel, α9 Gen5 AI Processor 4K, Brightness Booster, Dolby Vision IQ, and Dolby Atmos audio.",
    frontViewImage: "/products/lg-c2-front.webp",
    sideViewImage: "/products/lg-c2-side.webp",
    backViewImage: "/products/lg-c2-back.webp",
  },
  {
    id: "TV-205",
    name: "LG QNED80 4K QNED Smart TV (2023)",
    brand: "LG",
    category: "TVs",
    basePrice: 1750,
    sizes: "55 Inch (+AED 0) | 65 Inch (+AED 650) | 75 Inch (+AED 1500)",
    colors: "Ashen Blue",
    shortDescription: "Quantum Dot NanoCell 4K TV with α7 AI Processor Gen6 & 120Hz.",
    description: "Combines Quantum Dot and NanoCell technologies for rich, vibrant colors. Features Dimming Pro, 120Hz native refresh rate, and Game Optimizer.",
    frontViewImage: "/products/lg-qned80-front.webp",
    sideViewImage: "/products/lg-qned80-side.webp",
    backViewImage: "/products/lg-qned80-back.webp",
  },

  // ==========================================
  // 3. SONY (2022 - 2026 Models)
  // ==========================================
  {
    id: "TV-301",
    name: "Sony BRAVIA 8 OLED 4K Smart TV (2024)",
    brand: "Sony",
    category: "TVs",
    basePrice: 4400,
    sizes: "55 Inch (+AED 0) | 65 Inch (+AED 1500) | 77 Inch (+AED 3600)",
    colors: "Black",
    shortDescription: "2024 BRAVIA OLED with XR Processor & Acoustic Surface Audio+.",
    description: "Sony's 2024 BRAVIA OLED powered by XR Processor with Scene Recognition. Features Acoustic Surface Audio+ (screen is the speaker), Voice Zoom 3, and perfect integration with PlayStation 5.",
    frontViewImage: "/products/sony-bravia8-front.webp",
    sideViewImage: "/products/sony-bravia8-side.webp",
    backViewImage: "/products/sony-bravia8-back.webp",
  },
  {
    id: "TV-302",
    name: "Sony BRAVIA 9 Mini LED 4K TV (2024)",
    brand: "Sony",
    category: "TVs",
    basePrice: 5500,
    sizes: "65 Inch (+AED 0) | 75 Inch (+AED 2400) | 85 Inch (+AED 4800)",
    colors: "Black",
    shortDescription: "Sony's brightest 4K TV ever with High Peak Luminance Mini LED & XR Backlight Master Drive.",
    description: "The ultimate flagship Mini LED TV. Features XR Backlight Master Drive with world-leading backlight control, Beam Tweeter audio, Studio Calibrated modes, and 4K 120Hz HDMI 2.1.",
    frontViewImage: "/products/sony-bravia9-front.webp",
    sideViewImage: "/products/sony-bravia9-side.webp",
    backViewImage: "/products/sony-bravia9-back.webp",
  },
  {
    id: "TV-303",
    name: "Sony BRAVIA XR A80L OLED TV (2023)",
    brand: "Sony",
    category: "TVs",
    basePrice: 3300,
    sizes: "55 Inch (+AED 0) | 65 Inch (+AED 1100) | 77 Inch (+AED 2700) | 83 Inch (+AED 4500)",
    colors: "Black",
    shortDescription: "Cognitive Processor XR OLED TV with XR OLED Contrast Pro & Google TV.",
    description: "Cognitive Processor XR delivers pure OLED blacks and intense highlights. Features Acoustic Surface Audio+, Auto HDR Tone Mapping for PS5, and hands-free Google Assistant.",
    frontViewImage: "/products/sony-a80l-front.webp",
    sideViewImage: "/products/sony-a80l-side.webp",
    backViewImage: "/products/sony-a80l-back.webp",
  },
  {
    id: "TV-304",
    name: "Sony BRAVIA XR X90L Full Array LED (2023)",
    brand: "Sony",
    category: "TVs",
    basePrice: 2300,
    sizes: "55 Inch (+AED 0) | 65 Inch (+AED 700) | 75 Inch (+AED 1600) | 85 Inch (+AED 3100)",
    colors: "Dark Silver",
    shortDescription: "Full Array LED 4K TV with Cognitive Processor XR & 120Hz.",
    description: "Full Array LED with local dimming controlled by Cognitive Processor XR. Perfect for PS5 gaming with Auto Game Mode, HDMI 2.1 4K 120, and VRR.",
    frontViewImage: "/products/sony-x90l-front.webp",
    sideViewImage: "/products/sony-x90l-side.webp",
    backViewImage: "/products/sony-x90l-back.webp",
  },
  {
    id: "TV-305",
    name: "Sony BRAVIA XR A80K OLED TV (2022)",
    brand: "Sony",
    category: "TVs",
    basePrice: 2500,
    sizes: "55 Inch (+AED 0) | 65 Inch (+AED 900) | 77 Inch (+AED 2200)",
    colors: "Titan Black",
    shortDescription: "2022 Cognitive Processor XR OLED TV with Acoustic Surface Audio+.",
    description: "OLED display with Cognitive Processor XR, XR OLED Contrast Pro, Google TV smart platform, and BRAVIA CAM support.",
    frontViewImage: "/products/sony-a80k-front.webp",
    sideViewImage: "/products/sony-a80k-side.webp",
    backViewImage: "/products/sony-a80k-back.webp",
  },

  // ==========================================
  // 4. TCL (2022 - 2026 Models)
  // ==========================================
  {
    id: "TV-401",
    name: "TCL QM8 QD-Mini LED 4K Smart TV (2024)",
    brand: "TCL",
    category: "TVs",
    basePrice: 3200,
    sizes: "65 Inch (+AED 0) | 75 Inch (+AED 1400) | 85 Inch (+AED 2800) | 98 Inch (+AED 6500)",
    colors: "Black Metallic",
    shortDescription: "5000+ Nits Peak Brightness QD-Mini LED 4K TV with 144Hz VRR & Onkyo 2.1.2 Audio.",
    description: "TCL's flagship 2024 QD-Mini LED TV. Boasts up to 5,000 nits peak brightness, 5,000+ local dimming zones, AIPQ Ultra Processor, 144Hz VRR Game Accelerator 240, and Onkyo 2.1.2 sound system.",
    frontViewImage: "/products/tcl-qm8-front.webp",
    sideViewImage: "/products/tcl-qm8-side.webp",
    backViewImage: "/products/tcl-qm8-back.webp",
  },
  {
    id: "TV-402",
    name: "TCL C845 Mini LED 4K TV (2023)",
    brand: "TCL",
    category: "TVs",
    basePrice: 2400,
    sizes: "55 Inch (+AED 0) | 65 Inch (+AED 800) | 75 Inch (+AED 1800) | 85 Inch (+AED 3200)",
    colors: "Titanium",
    shortDescription: "2000 Nits Mini LED 4K TV with Quantum Dot & 144Hz VRR.",
    description: "Mini LED technology with Quantum Dot color, 2000 nits HDR brightness, AiPQ Processor 3.0, 144Hz VRR, Dolby Vision IQ, and IMAX Enhanced certification.",
    frontViewImage: "/products/tcl-c845-front.webp",
    sideViewImage: "/products/tcl-c845-side.webp",
    backViewImage: "/products/tcl-c845-back.webp",
  },
  {
    id: "TV-403",
    name: "TCL C745 QLED Gaming TV (2023)",
    brand: "TCL",
    category: "TVs",
    basePrice: 1650,
    sizes: "55 Inch (+AED 0) | 65 Inch (+AED 550) | 75 Inch (+AED 1300)",
    colors: "Dark Gray",
    shortDescription: "QLED 4K TV with 144Hz Full Array Local Dimming & Game Master 2.0.",
    description: "Engineered for gamers. QLED 1 billion colors, Full Array Local Dimming, 144Hz native refresh rate, AMD FreeSync Premium Pro, and Google TV.",
    frontViewImage: "/products/tcl-c745-front.webp",
    sideViewImage: "/products/tcl-c745-side.webp",
    backViewImage: "/products/tcl-c745-back.webp",
  },
  {
    id: "TV-404",
    name: "TCL C835 Mini LED 4K TV (2022)",
    brand: "TCL",
    category: "TVs",
    basePrice: 1900,
    sizes: "55 Inch (+AED 0) | 65 Inch (+AED 650) | 75 Inch (+AED 1500)",
    colors: "Black",
    shortDescription: "2022 Mini LED 4K TV with 144Hz VRR & Onkyo 2.1 Sound.",
    description: "Mini LED + QLED technology, 144Hz VRR refresh rate, Dolby Vision IQ, HDR10+, Onkyo 2.1 channel sound system, and Google TV platform.",
    frontViewImage: "/products/tcl-c835-front.webp",
    sideViewImage: "/products/tcl-c835-side.webp",
    backViewImage: "/products/tcl-c835-back.webp",
  },
  {
    id: "TV-405",
    name: "TCL P735 4K HDR Google TV (2022)",
    brand: "TCL",
    category: "TVs",
    basePrice: 950,
    sizes: "50 Inch (+AED 0) | 55 Inch (+AED 200) | 65 Inch (+AED 500) | 75 Inch (+AED 1100)",
    colors: "Black Metallic",
    shortDescription: "Edgeless 4K HDR Smart TV with Wide Color Gamut & Dolby Vision.",
    description: "Edgeless metallic frame design, 4K HDR with Wide Color Gamut, Dolby Vision & Dolby Atmos, MEMC motion clarity, and Google TV with hands-free voice control.",
    frontViewImage: "/products/tcl-p735-front.webp",
    sideViewImage: "/products/tcl-p735-side.webp",
    backViewImage: "/products/tcl-p735-back.webp",
  },
];

const headers = [
  "Product ID",
  "Product Name",
  "Brand",
  "Category",
  "Base Price (AED)",
  "Screen Size Options & Price Boosts",
  "Available Colors",
  "Short Description",
  "Full Description",
  "Front View Image Path",
  "Side View Image Path",
  "Back View Image Path"
];

const csvRows = [
  headers.join(","),
  ...tvProducts.map((p) =>
    [
      `"${p.id}"`,
      `"${p.name}"`,
      `"${p.brand}"`,
      `"${p.category}"`,
      `"${p.basePrice}"`,
      `"${p.sizes}"`,
      `"${p.colors}"`,
      `"${p.shortDescription.replace(/"/g, '""')}"`,
      `"${p.description.replace(/"/g, '""')}"`,
      `"${p.frontViewImage}"`,
      `"${p.sideViewImage}"`,
      `"${p.backViewImage}"`
    ].join(",")
  )
];

const csvContent = csvRows.join("\n");
const outputPath = path.join(__dirname, "../smart_tvs_catalog.csv");

fs.writeFileSync(outputPath, csvContent);
console.log(`✅ Smart TVs (2022-2026) CSV Catalog File successfully created at:\n${outputPath}`);
