import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const laptopsProducts = [
  // ==========================================
  // 1. APPLE (MACBOOK PRO & MACBOOK AIR)
  // ==========================================
  {
    id: "LAP-101",
    name: "MacBook Pro 16 M3 Max (2023/2024)",
    brand: "Apple",
    category: "Laptops",
    basePrice: 6500,
    specs: "36GB RAM / 1TB SSD (+AED 0) | 48GB RAM / 1TB SSD (+AED 900) | 128GB RAM / 2TB SSD (+AED 2800)",
    colors: "Space Black, Silver",
    shortDescription: "Extreme Pro performance with M3 Max chip, 16.2-inch Liquid Retina XDR display & 22-hr battery.",
    description: "Apple's flagship laptop. 16.2-inch Liquid Retina XDR display with ProMotion 120Hz, M3 Max chip with up to 16-core CPU & 40-core GPU, hardware-accelerated ray tracing, and HDMI 2.1 port.",
    frontViewImage: "/products/macbook-pro-16-front.webp",
    sideViewImage: "/products/macbook-pro-16-side.webp",
    backViewImage: "/products/macbook-pro-16-back.webp",
  },
  {
    id: "LAP-102",
    name: "MacBook Pro 14 M3 Pro (2023/2024)",
    brand: "Apple",
    category: "Laptops",
    basePrice: 4800,
    specs: "18GB RAM / 512GB SSD (+AED 0) | 18GB RAM / 1TB SSD (+AED 650) | 36GB RAM / 1TB SSD (+AED 1600)",
    colors: "Space Black, Silver",
    shortDescription: "Pro power in a portable 14.2-inch Liquid Retina XDR size with M3 Pro chip.",
    description: "Packed with M3 Pro chip (11-core or 12-core CPU, up to 18-core GPU), 14.2-inch Liquid Retina XDR display, MagSafe 3 charging, SDXC card slot, and 18 hours of battery life.",
    frontViewImage: "/products/macbook-pro-14-front.webp",
    sideViewImage: "/products/macbook-pro-14-side.webp",
    backViewImage: "/products/macbook-pro-14-back.webp",
  },
  {
    id: "LAP-103",
    name: "MacBook Air 15 M3 (2024)",
    brand: "Apple",
    category: "Laptops",
    basePrice: 3400,
    specs: "8GB RAM / 256GB SSD (+AED 0) | 16GB RAM / 512GB SSD (+AED 700) | 24GB RAM / 1TB SSD (+AED 1600)",
    colors: "Midnight, Starlight, Space Gray, Silver",
    shortDescription: "Ultra-thin 15.3-inch Liquid Retina laptop with M3 chip & dual external display support.",
    description: "Strikingly thin design with 15.3-inch Liquid Retina display, M3 chip, support for up to two external displays, MagSafe 3, 1080p FaceTime HD camera, and fanless silent operation.",
    frontViewImage: "/products/macbook-air-15-front.webp",
    sideViewImage: "/products/macbook-air-15-side.webp",
    backViewImage: "/products/macbook-air-15-back.webp",
  },
  {
    id: "LAP-104",
    name: "MacBook Air 13 M3 (2024)",
    brand: "Apple",
    category: "Laptops",
    basePrice: 2900,
    specs: "8GB RAM / 256GB SSD (+AED 0) | 16GB RAM / 512GB SSD (+AED 650) | 24GB RAM / 512GB SSD (+AED 1300)",
    colors: "Midnight, Starlight, Space Gray, Silver",
    shortDescription: "Ultra-portable 13.6-inch laptop with M3 performance.",
    description: "Supercharged by the M3 chip in an ultra-portable 13.6-inch Liquid Retina size. Features Wi-Fi 6E, MagSafe charging, 18-hour battery, and sleek aluminum unibody.",
    frontViewImage: "/products/macbook-air-13-front.webp",
    sideViewImage: "/products/macbook-air-13-side.webp",
    backViewImage: "/products/macbook-air-13-back.webp",
  },
  {
    id: "LAP-105",
    name: "MacBook Pro 16 M2 Max (2023)",
    brand: "Apple",
    category: "Laptops",
    basePrice: 4900,
    specs: "32GB RAM / 1TB SSD (+AED 0) | 64GB RAM / 1TB SSD (+AED 1200)",
    colors: "Space Gray, Silver",
    shortDescription: "2023 flagship 16-inch MacBook with M2 Max chip.",
    description: "M2 Max chip with 12-core CPU and up to 38-core GPU, 16.2-inch Liquid Retina XDR display, up to 96GB unified memory support, and HDMI 2.1 8K output.",
    frontViewImage: "/products/macbook-pro-16m2-front.webp",
    sideViewImage: "/products/macbook-pro-16m2-side.webp",
    backViewImage: "/products/macbook-pro-16m2-back.webp",
  },
  {
    id: "LAP-106",
    name: "MacBook Air 13 M2 (2022)",
    brand: "Apple",
    category: "Laptops",
    basePrice: 2200,
    specs: "8GB RAM / 256GB SSD (+AED 0) | 16GB RAM / 512GB SSD (+AED 550)",
    colors: "Midnight, Starlight, Space Gray, Silver",
    shortDescription: "Redesigned M2 MacBook Air with 13.6-inch Liquid Retina display.",
    description: "Radically redesigned around the M2 chip. Just 11.3 mm thin, 13.6-inch Liquid Retina display, MagSafe charging port, and 1080p camera.",
    frontViewImage: "/products/macbook-air-m2-front.webp",
    sideViewImage: "/products/macbook-air-m2-side.webp",
    backViewImage: "/products/macbook-air-m2-back.webp",
  },

  // ==========================================
  // 2. DELL & ALIENWARE
  // ==========================================
  {
    id: "LAP-201",
    name: "Dell XPS 16 9640 OLED (2024)",
    brand: "Dell",
    category: "Laptops",
    basePrice: 5200,
    specs: "16GB RAM / 512GB SSD (+AED 0) | 32GB RAM / 1TB SSD / RTX 4070 (+AED 1400) | 64GB RAM / 2TB SSD (+AED 3100)",
    colors: "Platinum, Graphite",
    shortDescription: "16.3-inch 4K+ OLED Touch ultrabook with Intel Core Ultra 7/9 & RTX 4070.",
    description: "Dell's premier 2024 laptop. Features a 16.3-inch 4K+ OLED touch screen, CNC machined aluminum chassis, seamless glass haptic touchpad, and RTX 4070 graphics.",
    frontViewImage: "/products/dell-xps16-front.webp",
    sideViewImage: "/products/dell-xps16-side.webp",
    backViewImage: "/products/dell-xps16-back.webp",
  },
  {
    id: "LAP-202",
    name: "Dell XPS 14 9440 (2024)",
    brand: "Dell",
    category: "Laptops",
    basePrice: 4200,
    specs: "16GB RAM / 512GB SSD (+AED 0) | 32GB RAM / 1TB SSD / RTX 4050 (+AED 950)",
    colors: "Platinum, Graphite",
    shortDescription: "Compact 14.5-inch 3.2K OLED laptop with Intel Core Ultra 7.",
    description: "Ultra-portable performance featuring 14.5-inch 3.2K 120Hz OLED touch display, Intel Core Ultra 7 processor with AI NPU, and discrete RTX 4050 GPU.",
    frontViewImage: "/products/dell-xps14-front.webp",
    sideViewImage: "/products/dell-xps14-side.webp",
    backViewImage: "/products/dell-xps14-back.webp",
  },
  {
    id: "LAP-203",
    name: "Dell Alienware m16 R2 Gaming Laptop (2024)",
    brand: "Dell",
    category: "Laptops",
    basePrice: 4600,
    specs: "16GB RAM / 1TB SSD (+AED 0) | 32GB RAM / 1TB SSD / RTX 4070 (+AED 900) | 64GB RAM / 2TB SSD (+AED 2200)",
    colors: "Dark Metallic Moon",
    shortDescription: "Intel Core Ultra 7 / 9 gaming laptop with RTX 4070 & 240Hz QHD+ screen.",
    description: "Redesigned Alienware chassis with Stealth Mode key, Cryo-tech cooling system, Intel Core Ultra processors, RTX 4070 graphics, and 240Hz QHD+ display.",
    frontViewImage: "/products/alienware-m16r2-front.webp",
    sideViewImage: "/products/alienware-m16r2-side.webp",
    backViewImage: "/products/alienware-m16r2-back.webp",
  },
  {
    id: "LAP-204",
    name: "Dell XPS 13 Plus 9320 (2023)",
    brand: "Dell",
    category: "Laptops",
    basePrice: 3100,
    specs: "16GB RAM / 512GB SSD (+AED 0) | 32GB RAM / 1TB SSD (+AED 750)",
    colors: "Platinum, Graphite",
    shortDescription: "Futuristic 13.4-inch 3.5K OLED touch ultrabook with capacitive function row.",
    description: "Futuristic borderless glass design, hidden haptic touchpad, zero-lattice keyboard, capacitive touch function row, and 3.5K OLED touchscreen.",
    frontViewImage: "/products/dell-xps13plus-front.webp",
    sideViewImage: "/products/dell-xps13plus-side.webp",
    backViewImage: "/products/dell-xps13plus-back.webp",
  },

  // ==========================================
  // 3. HP (SPECTRE, OMEN, ENVY, ELITEBOOK)
  // ==========================================
  {
    id: "LAP-301",
    name: "HP Spectre x360 14 (2024)",
    brand: "HP",
    category: "Laptops",
    basePrice: 3400,
    specs: "16GB RAM / 512GB SSD (+AED 0) | 16GB RAM / 1TB SSD (+AED 450) | 32GB RAM / 2TB SSD (+AED 1200)",
    colors: "Nightfall Black, Slate Blue, Sahara Silver",
    shortDescription: "2-in-1 14-inch 2.8K 120Hz OLED convertible with Intel Core Ultra 7 & haptic trackpad.",
    description: "Flagship 2-in-1 convertible laptop. 14-inch 2.8K OLED 120Hz variable refresh touchscreen, Intel Core Ultra 7 processor with AI engine, 9MP camera with hardware shutter, and Poly Studio audio.",
    frontViewImage: "/products/hp-spectre14-front.webp",
    sideViewImage: "/products/hp-spectre14-side.webp",
    backViewImage: "/products/hp-spectre14-back.webp",
  },
  {
    id: "LAP-302",
    name: "HP OMEN 16 Gaming Laptop (2024)",
    brand: "HP",
    category: "Laptops",
    basePrice: 3600,
    storages: "16GB RAM / 512GB SSD (+AED 0) | 16GB RAM / 1TB SSD / RTX 4070 (+AED 850) | 32GB RAM / 1TB SSD (+AED 1400)",
    colors: "Shadow Black",
    shortDescription: "Intel i7-14700HX / RTX 4070 gaming notebook with 165Hz QHD display.",
    description: "High-performance gaming equipped with 14th Gen Intel Core i7-14700HX, NVIDIA GeForce RTX 4070, Tempest Cooling 5-way airflow, and RGB per-key keyboard.",
    frontViewImage: "/products/hp-omen16-front.webp",
    sideViewImage: "/products/hp-omen16-side.webp",
    backViewImage: "/products/hp-omen16-back.webp",
  },
  {
    id: "LAP-303",
    name: "HP Envy x360 15 (2023)",
    brand: "HP",
    category: "Laptops",
    basePrice: 2200,
    specs: "16GB RAM / 512GB SSD (+AED 0) | 16GB RAM / 1TB SSD (+AED 400)",
    colors: "Nightfall Black, Natural Silver",
    shortDescription: "15.6-inch OLED touchscreen 2-in-1 with AMD Ryzen 7 / Intel Core i7.",
    description: "Versatile 15.6-inch convertible featuring IMAX Enhanced OLED touch display, Bang & Olufsen tuned quad speakers, and HP QuickDrop wireless file sharing.",
    frontViewImage: "/products/hp-envy15-front.webp",
    sideViewImage: "/products/hp-envy15-side.webp",
    backViewImage: "/products/hp-envy15-back.webp",
  },
  {
    id: "LAP-304",
    name: "HP EliteBook 840 G10 (2023)",
    brand: "HP",
    category: "Laptops",
    basePrice: 2800,
    specs: "16GB RAM / 512GB SSD (+AED 0) | 32GB RAM / 1TB SSD (+AED 700)",
    colors: "Pike Silver",
    shortDescription: "14-inch enterprise business laptop with Intel vPro & Sure View privacy screen.",
    description: "Commercial enterprise notebook with 13th Gen Intel Core vPro processors, HP Wolf Security, 5MP Auto Frame camera, and lightweight magnesium chassis.",
    frontViewImage: "/products/hp-elitebook-front.webp",
    sideViewImage: "/products/hp-elitebook-side.webp",
    backViewImage: "/products/hp-elitebook-back.webp",
  },

  // ==========================================
  // 4. LENOVO (THINKPAD, LEGION, YOGA)
  // ==========================================
  {
    id: "LAP-401",
    name: "Lenovo ThinkPad X1 Carbon Gen 12 (2024)",
    brand: "Lenovo",
    category: "Laptops",
    basePrice: 4500,
    specs: "16GB RAM / 512GB SSD (+AED 0) | 32GB RAM / 1TB SSD (+AED 900) | 64GB RAM / 2TB SSD (+AED 2100)",
    colors: "Eclipse Black Carbon",
    shortDescription: "Ultralight 14-inch 2.8K OLED business flagship with Intel Core Ultra & Communications Bar.",
    description: "The premier business laptop. 14-inch 2.8K 120Hz OLED screen, carbon fiber weave body, haptic glass TouchPad, Intel Core Ultra 7 processor, and legendary TrackPoint keyboard.",
    frontViewImage: "/products/lenovo-x1gen12-front.webp",
    sideViewImage: "/products/lenovo-x1gen12-side.webp",
    backViewImage: "/products/lenovo-x1gen12-back.webp",
  },
  {
    id: "LAP-402",
    name: "Lenovo Legion Pro 7i (2024)",
    brand: "Lenovo",
    category: "Laptops",
    basePrice: 5800,
    specs: "32GB RAM / 1TB SSD / RTX 4080 (+AED 0) | 32GB RAM / 2TB SSD / RTX 4090 (+AED 2400)",
    colors: "Eclipse Gray",
    shortDescription: "Ultra gaming flagship with Intel i9-14900HX, RTX 4080/4090 & 240Hz 500 nits display.",
    description: "Lenovo's ultimate gaming machine. Powered by Intel Core i9-14900HX, NVIDIA RTX 4080/4090 GPU, LA2-Q AI chip, Legion Coldfront Vapor chamber cooling, and 240Hz WQXGA display.",
    frontViewImage: "/products/lenovo-legion7i-front.webp",
    sideViewImage: "/products/lenovo-legion7i-side.webp",
    backViewImage: "/products/lenovo-legion7i-back.webp",
  },
  {
    id: "LAP-403",
    name: "Lenovo Yoga Book 9i Dual OLED (2023/2024)",
    brand: "Lenovo",
    category: "Laptops",
    basePrice: 4900,
    specs: "16GB RAM / 512GB SSD (+AED 0) | 16GB RAM / 1TB SSD (+AED 600)",
    colors: "Tidal Teal",
    shortDescription: "World's first full-size dual-screen 13.3-inch 2.8K OLED laptop with folio stand & pen.",
    description: "Revolutionary dual 13.3-inch 2.8K OLED touchscreens. Use in Laptop, Dual Screen, Tablet, or Book mode with included Bluetooth keyboard, Digital Pen 2, and Bowers & Wilkins soundbar hinge.",
    frontViewImage: "/products/lenovo-yogabook9i-front.webp",
    sideViewImage: "/products/lenovo-yogabook9i-side.webp",
    backViewImage: "/products/lenovo-yogabook9i-back.webp",
  },
  {
    id: "LAP-404",
    name: "Lenovo Legion Pro 5 (2023)",
    brand: "Lenovo",
    category: "Laptops",
    basePrice: 3200,
    specs: "16GB RAM / 512GB SSD (+AED 0) | 16GB RAM / 1TB SSD / RTX 4060 (+AED 600)",
    colors: "Onyx Grey",
    shortDescription: "AMD Ryzen 7 7745HX & RTX 4060 gaming notebook with 240Hz screen.",
    description: "AI-tuned gaming notebook featuring AMD Ryzen 7 processor, NVIDIA GeForce RTX 4060, Legion Coldfront 5.0 thermal tuning, and 16-inch WQXGA 240Hz panel.",
    frontViewImage: "/products/lenovo-legion5-front.webp",
    sideViewImage: "/products/lenovo-legion5-side.webp",
    backViewImage: "/products/lenovo-legion5-back.webp",
  },

  // ==========================================
  // 5. ASUS (ROG, ZENBOOK, TUF)
  // ==========================================
  {
    id: "LAP-501",
    name: "Asus ROG Zephyrus G16 OLED (2024)",
    brand: "Asus",
    category: "Laptops",
    basePrice: 5100,
    specs: "16GB RAM / 1TB SSD (+AED 0) | 32GB RAM / 1TB SSD / RTX 4070 (+AED 1100) | 32GB RAM / 2TB SSD / RTX 4080 (+AED 2600)",
    colors: "Eclipse Gray, Platinum White",
    shortDescription: "0.59-inch ultra-slim CNC gaming laptop with 2.5K 240Hz ROG Nebula OLED display.",
    description: "Impossibly thin CNC aluminum chassis with Slash Lighting array. 16-inch 2.5K 240Hz ROG Nebula OLED display, Intel Core Ultra 9 185H, RTX 4070/4080 graphics, and tri-fan thermal tech.",
    frontViewImage: "/products/asus-zephyrusg16-front.webp",
    sideViewImage: "/products/asus-zephyrusg16-side.webp",
    backViewImage: "/products/asus-zephyrusg16-back.webp",
  },
  {
    id: "LAP-502",
    name: "Asus Zenbook 14 OLED (2024)",
    brand: "Asus",
    category: "Laptops",
    basePrice: 2800,
    specs: "16GB RAM / 512GB SSD (+AED 0) | 16GB RAM / 1TB SSD (+AED 450) | 32GB RAM / 1TB SSD (+AED 900)",
    colors: "Ponder Blue, Foggy Silver",
    shortDescription: "Ultra-thin 1.2kg laptop with 3K 120Hz ASUS Lumina OLED & Intel Core Ultra 7.",
    description: "Lightweight 1.2 kg all-metal chassis. 14-inch 3K 120Hz ASUS Lumina OLED display, Intel Core Ultra 7 with AI Boost NPU, 75Wh long-lasting battery, and Harman Kardon audio.",
    frontViewImage: "/products/asus-zenbook14-front.webp",
    sideViewImage: "/products/asus-zenbook14-side.webp",
    backViewImage: "/products/asus-zenbook14-back.webp",
  },
  {
    id: "LAP-503",
    name: "Asus ROG Strix SCAR 18 (2024)",
    brand: "Asus",
    category: "Laptops",
    basePrice: 6900,
    specs: "32GB RAM / 2TB SSD / RTX 4080 (+AED 0) | 64GB RAM / 2TB SSD / RTX 4090 (+AED 2800)",
    colors: "Off Black",
    shortDescription: "18-inch 2.5K 240Hz Mini LED gaming titan with Intel i9-14900HX & RTX 4090.",
    description: "Dominant 18-inch ROG Nebula HDR Mini LED display with 2000+ dimming zones, Intel Core i9-14900HX, NVIDIA RTX 4090, Conductonaut Extreme liquid metal thermal compound.",
    frontViewImage: "/products/asus-scar18-front.webp",
    sideViewImage: "/products/asus-scar18-side.webp",
    backViewImage: "/products/asus-scar18-back.webp",
  },
  {
    id: "LAP-504",
    name: "Asus TUF Gaming A15 (2023)",
    brand: "Asus",
    category: "Laptops",
    basePrice: 2400,
    specs: "16GB RAM / 512GB SSD (+AED 0) | 16GB RAM / 1TB SSD / RTX 4060 (+AED 550)",
    colors: "Mecha Gray",
    shortDescription: "Military-grade durable gaming laptop with AMD Ryzen 7 7735HS & RTX 4060.",
    description: "MIL-STD-810H military toughness with AMD Ryzen 7 7735HS processor, NVIDIA RTX 4060 GPU with MUX Switch & Advanced Optimus, 144Hz FHD screen, and 90Wh battery.",
    frontViewImage: "/products/asus-tufa15-front.webp",
    sideViewImage: "/products/asus-tufa15-side.webp",
    backViewImage: "/products/asus-tufa15-back.webp",
  },

  // ==========================================
  // 6. RAZER & ACER
  // ==========================================
  {
    id: "LAP-601",
    name: "Razer Blade 16 (2024)",
    brand: "Razer",
    category: "Laptops",
    basePrice: 6200,
    specs: "32GB RAM / 1TB SSD / RTX 4080 (+AED 0) | 32GB RAM / 2TB SSD / RTX 4090 (+AED 2500)",
    colors: "Anodized Black, Mercury White",
    shortDescription: "World's first 240Hz 16-inch OLED display with Intel i9-14900HX & RTX 4080/4090.",
    description: "Crafted from a single CNC aluminum block. World's first 16-inch 240Hz QHD+ OLED display, Intel Core i9-14900HX, RTX 4080/4090 GPU, and patented vapor chamber cooling.",
    frontViewImage: "/products/razer-blade16-front.webp",
    sideViewImage: "/products/razer-blade16-side.webp",
    backViewImage: "/products/razer-blade16-back.webp",
  },
  {
    id: "LAP-602",
    name: "Acer Predator Helios 16 (2024)",
    brand: "Acer",
    category: "Laptops",
    basePrice: 3800,
    specs: "16GB RAM / 1TB SSD / RTX 4070 (+AED 0) | 32GB RAM / 1TB SSD / RTX 4080 (+AED 1400)",
    colors: "Abyssal Black",
    shortDescription: "16-inch 240Hz WQXGA gaming notebook with 14th Gen Intel i9 & RTX 4070/4080.",
    description: "High-performance gaming machine with 14th Gen Intel Core i9, RTX 4070/4080 GPU, 5th Gen AeroBlade 3D fan cooling, and customizable RGB lighting bar.",
    frontViewImage: "/products/acer-helios16-front.webp",
    sideViewImage: "/products/acer-helios16-side.webp",
    backViewImage: "/products/acer-helios16-back.webp",
  },
];

const headers = [
  "Product ID",
  "Product Name",
  "Brand",
  "Category",
  "Base Price (AED)",
  "RAM / Storage Spec Variants & Price Boosts",
  "Available Colors",
  "Short Description",
  "Full Description",
  "Front View Image Path",
  "Side View Image Path",
  "Back View Image Path"
];

const csvRows = [
  headers.join(","),
  ...laptopsProducts.map((p) =>
    [
      `"${p.id}"`,
      `"${p.name}"`,
      `"${p.brand}"`,
      `"${p.category}"`,
      `"${p.basePrice}"`,
      `"${p.specs}"`,
      `"${p.colors}"`,
      `"${p.shortDescription.replace(/"/g, '""')}"`,
      `"${p.description.replace(/"/g, '""')}"`,
      `"${p.frontViewImage}"`,
      `"${p.sideViewImage}"`,
      `"${p.backViewImage}"`
    ].join(",")
  )
];

const csvContent = csvRows.join("\n");
const outputPath = path.join(__dirname, "../laptops_catalog.csv");

fs.writeFileSync(outputPath, csvContent);
console.log(`✅ Laptops CSV Catalog File successfully created at:\n${outputPath}`);
